Feature: Dependency management — Reproducible builds and version synchronization

  Background:
    Given a working hpx workspace with all crates compiled

  # --- Cargo.lock ---

  @finding-DEPS-05 @dependencies @priority-high
  Scenario: Workspace has a committed Cargo.lock for reproducible builds
    Given the workspace root Cargo.toml exists
    When the repository is cloned and cargo build is run
    Then a Cargo.lock SHALL exist in the repository root
    And the locked versions SHALL produce a successful build with all default features

  @finding-DEPS-05 @dependencies @priority-medium
  Scenario: Cargo.lock is regenerated by CI on dependency changes
    When a dependency version is changed in Cargo.toml
    And CI runs cargo update
    Then the updated Cargo.lock SHALL be committed automatically

  # --- AGENTS.md Version Sync ---

  @finding-DEPS-08 @dependencies @priority-high
  Scenario: AGENTS.md dependency versions match Cargo.toml
    Given the workspace root Cargo.toml defines workspace dependencies
    When AGENTS.md is read
    Then every dependency version in AGENTS.md SHALL match the corresponding entry in Cargo.toml

  @finding-DEPS-08 @dependencies @priority-medium
  Scenario: AGENTS.md version drift is detected in CI
    When a dependency version is updated in Cargo.toml without updating AGENTS.md
    Then CI SHALL report a version drift warning
